// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFoO-nCOrhVrilc0iWp2Q7lFNZmP-FcF0',
    appId: '1:113951040604:web:4304dc42ad18533bf97299',
    messagingSenderId: '113951040604',
    projectId: 'tithighadi-bb2c9',
    authDomain: 'tithighadi-bb2c9.firebaseapp.com',
    storageBucket: 'tithighadi-bb2c9.firebasestorage.app',
    measurementId: 'G-BQ8Q2BK6XG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs9Phf7Z7xvwrpiTlcAiuUYWQcGfO58TI',
    appId: '1:113951040604:android:fa373ab17ec7543df97299',
    messagingSenderId: '113951040604',
    projectId: 'tithighadi-bb2c9',
    storageBucket: 'tithighadi-bb2c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM4Yup1k3smFv_L70sFKHqdYWBnRrsK8w',
    appId: '1:113951040604:ios:1bb473835906b07df97299',
    messagingSenderId: '113951040604',
    projectId: 'tithighadi-bb2c9',
    storageBucket: 'tithighadi-bb2c9.firebasestorage.app',
    iosBundleId: 'com.example.tithiGadhi',
  );
}
